name: Minify Workflow
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: copy file
                uses: canastro/copy-file-action@master
                with:
                    source: "countdown.js"
                    target: "min/countdown.js"

            # Checks-out your repository
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}

            - name: Minify Action
              uses: anthonyftwang/minify-action@v1.0.1
              with:
                  directory: 'min'
                  overwrite: false

            # Auto-commit to repository
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Minify source code
                  branch: ${{ github.ref }}
